<?php
/**
 * @file
 */

define('EXCUR_CURRENCY_DEFAULT', variable_get('excur_currency_default'));

/**
 * Implements hook_ctools_plugin_directory().
 */
function excur_currency_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'panels') {
    return "plugins/$plugin_type";
  }

  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return "plugins/content_types";
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function excur_currency_choice_form() {
  $form['currency'] = array(
    '#type' => 'select',
    '#options' => array(
      'none' => t('Currency offers'),
      'EUR' => t('Euro'),
      'USD' => t('U.S. Dollar'),
      'RUB' => t('Russian Rouble'),
      'CAD' => t('Canadian Dollar'),
      'CZK' => t('Czech Koruna'),
      'JPY' => t('Japanese Yen'),
      'NZD' => t('New Zealand Dollar'),
      'GBP' => t('Pound sterling'),
      'CHF' => t('Swiss Franc'),
    ),
    '#default_value' => !empty($_COOKIE['currency']) ? $_COOKIE['currency'] : 'none',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Change currency'),
  );

  return $form;
}
