<?php

/**
 * @file.
 */


/**
 * Preprocess for excur-profile-form.tpl.php.
 */
function excur_preprocess_excur_profile_form(&$vars) {
  $vars['form']['account']['name']['#title'] = t('Login');

}

/**
 * Preprocess for excur-user-login-form.tpl.php.
 */
function excur_preprocess_excur_user_login_form(&$vars) {

}

/**
 * Preprocess for excur-user-register-form.tpl.php.
 */
function excur_preprocess_excur_user_register_form(&$vars) {

}

/**
 * Preprocess for excur-service_node-form.tpl.php.
 */
function excur_preprocess_excur_service_node_form(&$vars) {

}