<?php
/**
 * @file
 */

define('FRONT_THEME_PATH', drupal_get_path('theme', 'exc_theme'));

/**
 * Implements hook
 */
function excur_menu() {
  $items['admin/config/excur'] = array(
    'title' => 'Site settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('excur_settings_form'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function excur_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'panels') {
    return "plugins/$plugin_type";
  }

  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return "plugins/content_types";
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function excur_form_main_page_slider_node_form_alter(&$form, &$form_id) {
  if (empty($form['#node']->nid)) {
    $form['title']['#default_value'] = 'Слайдер главной страницы (' . date('d:m:Y') . ')';
  }
}

/**
 * Settings form for excur site.
 */
function excur_settings_form() {
  $form = array();

  return system_settings_form($form);
}

/**
 * Validate function for 'excur_settings_form' form.
 */
function excur_settings_form_validate(&$form, &$form_state) {

}

/**
 * Validate function for 'excur_settings_form' form.
 */
function excur_settings_form_submit(&$form, &$form_state) {

}

/**
 * Get images of main page slider.
 *
 * @return array.
 */
function excur_main_slider_images() {
  $nid = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('type', 'main_page_slider')
    ->orderBy('nid', 'DESC')
    ->range(0, 1)
    ->execute()
    ->fetchField();

  if ($nid) {
    $node = node_load($nid);
    return $node->field_slider_images[LANGUAGE_NONE];
  }

  return array();
}

/**
 * Get text blocks for main page.
 *
 * @return array.
 */
function excur_main_text_blocks() {
  global $language;

  $query = db_select('node', 'n');
  $query->fields('n', array('nid'));
  $query->join('entity_translation', 'et', 'et.entity_id = n.nid');
  $query->condition('n.type ', 'text_block');
  $query->condition('et.entity_type', 'node');
  $query->condition('et.language', $language->language);
  $nids = $query->execute()->fetchCol();

  if ($nids) {
    foreach ($nids as $nid) {
      $nodes[] = node_load($nid);
    }

    return $nodes;
  }

  return array();
}

/**
 * Get count of service in city.
 *
 * @param int $tid.
 * @return int.
 */
function excur_count_service_by_city($tid) {
  $query = db_select('field_data_field_city', 'fdfc');
  $query->fields('fdfc', array('entity_id'));
  $query->condition('fdfc.field_city_target_id', $tid);
  $query->condition('fdfc.bundle', 'service');
  $count = $query->execute()->rowCount();

  return $count ? $count : 0;
}

/**
 * Build the breadcrumb by current page.
 *
 * @return array.
 */
function excur_get_breadcrumb() {
  if ($node = menu_get_object()) {
    if ($node->type == 'service') {
      $city = taxonomy_term_load($node->field_city[LANGUAGE_NONE][0]['target_id']);
      $country = taxonomy_term_load($city->field_country[LANGUAGE_NONE][0]['target_id']);
      $continent = taxonomy_term_load($country->field_continent[LANGUAGE_NONE][0]['target_id']);

      $breadcrumb[] = l($continent->name, "taxonomy/term/$continent->tid");
      $breadcrumb[] = l($country->name, "taxonomy/term/$country->tid");
      $breadcrumb[] = l($city->name, "taxonomy/term/$city->tid");
      $breadcrumb[] = $node->title;
    }
    else {
      $breadcrumb[] = $node->title;
    }
  }
  elseif ($term = menu_get_object('taxonomy_term', 2)) {
    if ($term->vocabulary_machine_name == 'continent') {
      $breadcrumb[] = $term->name;
    }
    elseif ($term->vocabulary_machine_name == 'country') {
      $continent = taxonomy_term_load($term->field_continent[LANGUAGE_NONE][0]['target_id']);

      $breadcrumb[] = l($continent->name, "taxonomy/term/$continent->tid");
      $breadcrumb[] = $term->name;
    }
    elseif ($term->vocabulary_machine_name == 'city') {
      $country = taxonomy_term_load($term->field_country[LANGUAGE_NONE][0]['target_id']);
      $continent = taxonomy_term_load($country->field_continent[LANGUAGE_NONE][0]['target_id']);

      $breadcrumb[] = l($continent->name, "taxonomy/term/$continent->tid");
      $breadcrumb[] = l($country->name, "taxonomy/term/$country->tid");
      $breadcrumb[] = $term->name;
    }
  }

  if (isset($breadcrumb)) {
    array_unshift($breadcrumb, l(t('Home'), '<front>'));

    return $breadcrumb;
  }

  return array();
}

/**
 * Get most popular cities by country.
 *
 * @param int $tid.
 * @return array.
 */
function excur_popular_cities($tid) {
  global $language;

  $query = db_select('field_data_field_city', 'city');
  $query->fields('city', array('field_city_target_id'));
  $query->join('field_data_field_country', 'country', 'city.field_city_target_id = country.entity_id');
  $query->join('entity_translation', 'et', 'city.field_city_target_id = et.entity_id');
  $query->condition('city.bundle', 'service');
  $query->condition('country.bundle', 'city');
  $query->condition('et.entity_type', 'taxonomy_term');
  $query->condition('et.language', $language->language);
  $query->condition('country.field_country_target_id', $tid);
  $query->groupBy('city.field_city_target_id');
  $query->range(0, 6);

  return $query->execute()->fetchCol();
}

/**
 * Get count of guides by city.
 *
 * @param int $tid.
 * @return array.
 */
function excur_count_guide_by_city($tid) {
  $query = db_select('field_data_field_city', 'city');
  $query->fields('city', array('entity_id'));
  $query->condition('city.field_city_target_id', $tid);
  $query->condition('city.bundle', 'user');
  $count = $query->execute()->rowCount();

  return $count ? $count : 0;
}

/**
 * Get most popular giudes by country.
 *
 * @param int $tid.
 * @return array.
 */
function excur_popular_giudes_in_country($tid) {
  $query = db_select('users', 'u');
  $query->fields('u', array('uid'));
  $query->join('field_data_field_city', 'city', 'u.uid = city.entity_id');
  $query->join('field_data_field_country', 'country', 'city.field_city_target_id = country.entity_id');
  $query->condition('u.status', 1);
  $query->condition('city.bundle', 'user');
  $query->condition('country.bundle', 'city');
  $query->condition('country.field_country_target_id', $tid);
  $query->range(0, 6);

  return $query->execute()->fetchCol();
}

/**
 * Get most popular giudes by city.
 *
 * @param int $tid.
 * @return array.
 */
function excur_popular_giudes_in_city($tid) {

  return array();
}