<?php
/**
 * @file
 */

define('EXCUR_FRONT_THEME_PATH', drupal_get_path('theme', 'exc_theme'));
define('EXCUR_USER_ROLE_GUIDE_ID', 4);
define('EXCUR_USER_ROLE_GUIDE_NAME', 'Гид');

/**
 * Implements hook
 */
function excur_menu() {
  $items['admin/config/excur'] = array(
    'title' => 'Site settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('excur_settings_form'),
    'access arguments' => array('administer site configuration'),
  );

  $items['user/%user/bookings'] = array(
    'title' => 'Bookings',
    'page callback' => 'excur_user_bookings',
    'page arguments' => array(1),
    'access callback' => 'excur_user_page_access',
    'access arguments' => array(1),
  );

  $items['user/%user/order'] = array(
    'title' => 'Orders',
    'page callback' => 'excur_user_order',
    'page arguments' => array(1),
    'access callback' => 'excur_user_page_access',
    'access arguments' => array(1),
  );

  $items['user/%user/offer'] = array(
    'title' => 'Offers',
    'page callback' => 'excur_user_offers',
    'page arguments' => array(1),
    'access callback' => 'excur_user_page_access',
    'access arguments' => array(1),
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function excur_menu_alter(&$items) {

  $items['user/%user/edit']['title'] = 'Profile';
  $items['user/%user/view']['title'] = 'My offers';

  $items['user/%user/messages'] = array(
    'title' => 'Private messages',
    'page callback' => 'theme',
    'page arguments' => array('excur_user_messages'),
    'access callback' => 'excur_user_page_access',
    'access arguments' => array(1),
  );
  $items['user/%user/edit'] = array(
    'title' => 'Edit profile',
    'page callback' => 'excur_user_edit',
    'page arguments' => array(1),
    'access callback' => 'excur_user_page_access',
    'access arguments' => array(1),
  );
}

/**
 * Implements hook_init().
 */
function excur_init() {
  // Include necessary files for private messages.
  if (preg_match('/user\/[0-9]*\/messages/', current_path()) || (isset($_POST['form_id']) && $_POST['form_id'] == 'privatemsg_list')) {
    module_load_include('inc', 'privatemsg', 'privatemsg.pages');
  }
  elseif (preg_match('/user\/[0-9]*\/edit/', current_path()) || (isset($_POST['form_id']) && $_POST['form_id'] == 'user_profile_form')) {
    module_load_include('inc', 'user', 'user.pages');
  }
}

/**
 * Implement hook_theme().
 */
function excur_theme() {
  $theme['excur_user_messages'] = array(
    'template' => 'excur-user-messages',
    'variables' => array(
      'account' => NULL,
    ),
  );
  $theme['excur_user_edit'] = array(
    'template' => 'excur-user-edit',
    'variables' => array(
      'account' => NULL,
    ),
  );
  $theme['excur_user_menu'] = array(
    'template' => 'excur-user-menu',
    'variables' => array(
      'account' => NULL,
    ),
  );
  $theme['excur_profile_form'] = array(
    'file' => 'theme.inc',
    'path' => drupal_get_path('module', 'excur') . '/theme',
    'template' => 'excur-profile-form',
    'render element' => 'form',
  );
  $theme['excur_user_login_form'] = array(
    'file' => 'theme.inc',
    'path' => drupal_get_path('module', 'excur') . '/theme',
    'template' => 'excur-user-login-form',
    'render element' => 'form',
  );
  $theme['excur_user_register'] = array(
    'file' => 'theme.inc',
    'path' => drupal_get_path('module', 'excur') . '/theme',
    'template' => 'excur-user-register-form',
    'render element' => 'form',
  );
  $theme['excur_service_node'] = array(
    'file' => 'theme.inc',
    'path' => drupal_get_path('module', 'excur') . '/theme',
    'template' => 'excur-service-node-form',
    'render element' => 'form',
  );
  $theme['excur_user_bookings'] = array(
    'template' => 'excur-user-bookings',
  );
  $theme['excur_user_order'] = array(
    'template' => 'excur-user-order',
  );
  $theme['excur_user_offers'] = array(
    'template' => 'excur-user-offers',
  );

  return $theme;
}

/**
 * Page callback user/%user/bookings
 */
function excur_user_bookings($account) {
  return theme('excur_user_bookings', array('account' => $account));
}

/**
 * Page callback user/%user/offer
 */
function excur_user_offers($account) {
  return theme('excur_user_offers', array('account' => $account));;
}

/**
 * Page callback user/%user/order
 */
function excur_user_order($account) {
  return theme('excur_user_order', array('account' => $account));
}

/**
 * Access callback for user/%user/massages.
 */
function excur_user_page_access($account) {
  global $user;

  if ($user->uid == 1 || $account->uid == $user->uid) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Page callback for user/%user/edit.
 */
function excur_user_edit($account) {
  global $user;

  if ($user->uid == 1) {
    return drupal_get_form('user_profile_form', $account);
  }
  else {
    return theme('excur_user_edit', array('account' => $account));
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function excur_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'panels') {
    return "plugins/$plugin_type";
  }

  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return "plugins/content_types";
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function excur_form_service_node_form_alter(&$form, &$form_state) {
  if (!empty($_GET['guide']) && is_numeric($_GET['guide']) && $guide = user_load($_GET['guide'])) {
    $form['field_guide'][LANGUAGE_NONE][0]['target_id']['#value'] = $guide->field_name[LANGUAGE_NONE][0]['safe_value'] . " ($guide->uid)";
    $form['field_guide']['#attributes']['class'][] = 'element-hidden';
  }

  $form_state['buttons'][0]['#attributes']['class'][] = 'btn';
  $form['actions']['submit']['#attributes']['class'][] = 'btn';
  $form['actions']['delete']['#attributes']['class'][] = 'btn';
  $form['#theme'][] = 'excur_service_node';
  unset($form['actions']['preview_changes']);
  unset($form['form']['language']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function excur_form_main_page_slider_node_form_alter(&$form, &$form_state) {
  if (empty($form['#node']->nid)) {
    $form['title']['#default_value'] = 'Слайдер главной страницы (' . date('d:m:Y') . ')';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function excur_form_user_register_form_alter(&$form, &$form_state) {
  $form['#theme'][] = 'excur_user_register';
  $form['actions']['submit']['#attributes']['class'][] = 'btn';
  $form['account']['mail']['#description'] = t('Допускается использовать латинские буквы, цифры');
  $form['account']['pass']['#description'] = t('Допускается использовать латинские буквы, цифры');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function excur_form_user_profile_form_alter(&$form, &$form_state) {
  global $user;

  if (!$user->uid == 1 || empty($user->roles[3])) {
    $form['field_certified']['#access'] = FALSE;
  }
  if (!isset($user->roles[EXCUR_USER_ROLE_GUIDE_ID])) {
    $form['guide'] = array(
      '#type' => 'checkbox',
      '#title' => t('Become a guide'),
      '#default_value' => isset($user->roles[EXCUR_USER_ROLE_GUIDE_ID]) ? TRUE : FALSE,
    );
  }

  $form['actions']['submit']['#attributes']['class'][] = 'btn';
  $form['actions']['cancel']['#attributes']['class'][] = 'btn';
  $form['#submit'][] = 'excur_form_user_profile_form_submit';
  $form['#theme'][] = 'excur_profile_form';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function excur_form_user_login_alter(&$form, &$form_state) {
  $form['actions']['submit']['#attributes']['class'][] = 'btn';
  $form['#theme'][] = 'excur_user_login_form';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function excur_form_user_pass_alter(&$form, &$form_state) {
  $form['actions']['submit']['#attributes']['class'][] = 'btn';
}

/**
 * Custom submit for user_register_form() form.
 */
function excur_form_user_profile_form_submit(&$form, &$form_state) {
  if (!empty($form_state['values']['guide']) && $form_state['values']['guide']) {
    $form['#user']->roles[EXCUR_USER_ROLE_GUIDE_ID] = EXCUR_USER_ROLE_GUIDE_NAME;
    user_save($form['#user']);
  }
}

/**
 * Settings form for excur site.
 */
function excur_settings_form() {
  $form = array();

  return system_settings_form($form);
}

/**
 * Validate function for 'excur_settings_form' form.
 */
function excur_settings_form_validate(&$form, &$form_state) {

}

/**
 * Validate function for 'excur_settings_form' form.
 */
function excur_settings_form_submit(&$form, &$form_state) {

}

/**
 * Get images of main page slider.
 *
 * @return array.
 */
function excur_main_slider_images() {
  $nid = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('type', 'main_page_slider')
    ->orderBy('nid', 'DESC')
    ->range(0, 1)
    ->execute()
    ->fetchField();

  if ($nid) {
    $node = node_load($nid);
    return $node->field_slider_images[LANGUAGE_NONE];
  }

  return array();
}

/**
 * Get text blocks for main page.
 *
 * @return array.
 */
function excur_main_text_blocks() {
  global $language;

  $query = db_select('node', 'n');
  $query->fields('n', array('nid'));
  $query->join('entity_translation', 'et', 'et.entity_id = n.nid');
  $query->condition('n.type ', 'text_block');
  $query->condition('et.entity_type', 'node');
  $query->condition('et.language', $language->language);
  $nids = $query->execute()->fetchCol();

  if ($nids) {
    foreach ($nids as $nid) {
      $nodes[] = node_load($nid);
    }

    return $nodes;
  }

  return array();
}

/**
 * Get count of service in city.
 *
 * @param int $tid.
 * @return int.
 */
function excur_count_service_by_city($tid) {
  $query = db_select('field_data_field_city', 'fdfc');
  $query->fields('fdfc', array('entity_id'));
  $query->condition('fdfc.field_city_target_id', $tid);
  $query->condition('fdfc.bundle', 'service');
  $count = $query->execute()->rowCount();

  return $count ? $count : 0;
}

/**
 * Build the breadcrumb by current page.
 *
 * @return array.
 */
function excur_get_breadcrumb() {
  if ($node = menu_get_object()) {
    if ($node->type == 'service') {
      $city = taxonomy_term_load($node->field_city[LANGUAGE_NONE][0]['target_id']);
      $country = taxonomy_term_load($city->field_country[LANGUAGE_NONE][0]['target_id']);
      $continent = taxonomy_term_load($country->field_continent[LANGUAGE_NONE][0]['target_id']);

      $breadcrumb[] = l($continent->name, "taxonomy/term/$continent->tid");
      $breadcrumb[] = l($country->name, "taxonomy/term/$country->tid");
      $breadcrumb[] = l($city->name, "taxonomy/term/$city->tid");
      $breadcrumb[] = $node->title;
    }
    else {
      $breadcrumb[] = $node->title;
    }
  }
  elseif ($term = menu_get_object('taxonomy_term', 2)) {
    if ($term->vocabulary_machine_name == 'continent') {
      $breadcrumb[] = $term->name;
    }
    elseif ($term->vocabulary_machine_name == 'country') {
      $continent = taxonomy_term_load($term->field_continent[LANGUAGE_NONE][0]['target_id']);

      $breadcrumb[] = l($continent->name, "taxonomy/term/$continent->tid");
      $breadcrumb[] = $term->name;
    }
    elseif ($term->vocabulary_machine_name == 'city') {
      $country = taxonomy_term_load($term->field_country[LANGUAGE_NONE][0]['target_id']);
      $continent = taxonomy_term_load($country->field_continent[LANGUAGE_NONE][0]['target_id']);

      $breadcrumb[] = l($continent->name, "taxonomy/term/$continent->tid");
      $breadcrumb[] = l($country->name, "taxonomy/term/$country->tid");
      $breadcrumb[] = $term->name;
    }
  }

  if (isset($breadcrumb)) {
    array_unshift($breadcrumb, l(t('Home'), '<front>'));

    return $breadcrumb;
  }

  return array();
}

/**
 * Get most popular cities by country.
 *
 * @param int $tid.
 * @return array.
 */
function excur_popular_cities($tid) {
  global $language;

  $query = db_select('field_data_field_city', 'city');
  $query->fields('city', array('field_city_target_id'));
  $query->join('field_data_field_country', 'country', 'city.field_city_target_id = country.entity_id');
  $query->join('entity_translation', 'et', 'city.field_city_target_id = et.entity_id');
  $query->condition('city.bundle', 'service');
  $query->condition('country.bundle', 'city');
  $query->condition('et.entity_type', 'taxonomy_term');
  $query->condition('et.language', $language->language);
  $query->condition('country.field_country_target_id', $tid);
  $query->groupBy('city.field_city_target_id');
  $query->range(0, 6);

  return $query->execute()->fetchCol();
}

/**
 * Get count of guides by city.
 *
 * @param int $tid.
 * @return array.
 */
function excur_count_guide_by_city($tid) {
  $query = db_select('field_data_field_city', 'city');
  $query->fields('city', array('entity_id'));
  $query->condition('city.field_city_target_id', $tid);
  $query->condition('city.bundle', 'user');
  $count = $query->execute()->rowCount();

  return $count ? $count : 0;
}

/**
 * Get most popular giudes by country.
 *
 * @param int $tid.
 * @return array.
 */
function excur_popular_giudes_in_country($tid) {
  $query = db_select('users', 'u');
  $query->fields('u', array('uid'));
  $query->join('field_data_field_city', 'city', 'u.uid = city.entity_id');
  $query->join('field_data_field_country', 'country', 'city.field_city_target_id = country.entity_id');
  $query->join('votingapi_cache', 'vc', 'vc.entity_id = u.uid AND vc.entity_type = \'user\' AND vc.function = \'average\'');
  $query->condition('u.status', 1);
  $query->condition('city.bundle', 'user');
  $query->condition('country.bundle', 'city');
  $query->condition('country.field_country_target_id', $tid);
  $query->orderBy('vc.value', 'DESC');
  $query->range(0, 6);

  return $query->execute()->fetchCol();
}

/**
 * Get most popular giudes by city.
 *
 * @param int $tid.
 * @return array.
 */
function excur_popular_giudes_in_city($tid) {
  $query = db_select('users', 'u');
  $query->fields('u', array('uid'));
  $query->join('field_data_field_city', 'city', 'u.uid = city.entity_id');
  $query->join('votingapi_cache', 'vc', 'vc.entity_id = u.uid AND vc.entity_type = \'user\' AND vc.function = \'average\'');
  $query->condition('u.status', 1);
  $query->condition('city.bundle', 'user');
  $query->condition('city.field_city_target_id', $tid);
  $query->orderBy('vc.value', 'DESC');
  $query->range(0, 6);

  return $query->execute()->fetchCol();
}

/**
 * Language switcher form.
 */
function excur_language_switcher() {
  $options = array();
  $data_content = array();

  foreach (language_list() as $lang) {
    if ($lang->enabled) {
      $url = url(current_path(), array('language' => $lang, 'absolute' => TRUE));
      $options[$url] = $lang->native;
      $langcode = explode('-', $lang->prefix);
      $data_content[$url] = '<i class=\'flag flag-' . reset($langcode) . '\'></i>' . $lang->native;
    }
  }

  $form['languages'] = array(
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => url(current_path(), array('absolute' => TRUE)),
    '#data-content' => $data_content,
  );

  return $form;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function excur_form_views_exposed_form_alter(&$form, &$form_state) {
  if ($form['#id'] == "views-exposed-form-content-city-service"
    || $form['#id'] == "views-exposed-form-content-guide-service") {

    $form['submit']['#attributes']['class'][] = 'btn';
    $form['field_languages_tid']['#attributes']['title'] = t('Use all languages');
  }
}

/**
 * Get categories of all services in city.
 *
 * @param int $city.
 * @return array.
 */
function excur_categories_by_city($city) {
  global $language;

  $query = db_select('field_data_name_field', 'name');
  $query->fields('name', array('entity_id', 'name_field_value'));
  $query->fields('tth', array('parent'));
  $query->join('field_data_field_category', 'category', 'name.entity_id = category.field_category_tid');
  $query->join('field_data_field_city', 'city', 'city.entity_id = category.entity_id');
  $query->join('taxonomy_term_hierarchy', 'tth', 'tth.tid = category.field_category_tid');
  $query->condition('name.bundle', 'category');
  $query->condition('name.language', $language->language);
  $query->condition('city.field_city_target_id', $city);

  return $query->execute()->fetchAll();
}

/**
 * Draw user menu.
 */
function excur_user_menu($account) {
  return theme('excur_user_menu', array('account' => $account));
}

/**
 *
 */
function excur_guide_logo($account, $style, $attributes = array()) {
  if (!empty($account->field_image[LANGUAGE_NONE])) {
    $path = $account->field_image[LANGUAGE_NONE][0]['uri'];
    $theming = 'image_style';
  }
  else {
    $path = EXCUR_FRONT_THEME_PATH . '/images/user-default.png';
    $theming = 'remote_image_style';
  }

  return theme($theming, array(
    'style_name' => $style,
    'path' => $path,
    'alt' => $account->field_name[LANGUAGE_NONE][0]['safe_value'],
    'title' => $account->field_name[LANGUAGE_NONE][0]['safe_value'],
    'attributes' => $attributes,
  ));
}
