<?php

/**
 * @file.
 */

define('EXCUR_OFFER_NOT_CONFIRMED', 'not_confirmed');
define('EXCUR_OFFER_CONFIRMED', 'confirmed');
define('EXCUR_OFFER_REJECTED', 'rejected');

// Include additional files.
require_once 'excur_offer.mail.inc';

/**
 * Implements hook_menu().
 */
function excur_offer_menu() {
  $items['excur/offer/%excur_offer'] = array(
    'title' => 'E-ticket',
    'page callback' => 'excur_offer_page',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
  );
  $items['excur/offer/confirm/%excur_offer'] = array(
    'title' => 'confirmed',
    'page callback' => 'excur_offer_confirmed',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
  );
  $items['excur/offer/reject/%excur_offer'] = array(
    'title' => 'confirmed',
    'page callback' => 'excur_offer_rejected',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
  );
    $items['excur/offer/order/%node'] = array(
    'title' => 'order',
    'page callback' => 'excur_offer_order',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
  );
    
  return $items;
}

/**
 * Implement hook_theme().
 */
function excur_offer_theme() {
  $items['excur_offer_offer_form'] = array(
    'template' => 'theme/offer-form',
    'render element' => 'form',
  );

  $items['offer_mail'] = array(
    'file' => 'theme.inc',
    'path' => drupal_get_path('module', 'excur_offer') . '/theme',
    'variables' => array(
      'offer' => NULL,
    ),
    'template' => 'offer-mail',
  );

    $items['order_template'] = array(
        'order_template' => array(
            'variables' => array(
            'body' => NULL,
            'title' => NULL,
        ),
            'template' => 'order-template.tpl.php',
        ),
    );
  
      $items['excur_offer_order_form'] = array(
            'render element' => 'form',
            'template' => 'order-template.tpl.php',
    );
  return $items;
}

/**
 * Implements hook_views_api().
 */
function excur_offer_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Page callback for excur/offer/%excur_offer path.
 */
function excur_offer_confirmed($offer) {
  excur_offer_update($offer->id, 'status', EXCUR_OFFER_CONFIRMED);
  $account = user_load($offer->uid);
  $message = theme('offer_mail', array(
    'offer' => $offer,
  ));
  excur_offer_send_mail($account->mail, $message);
  print t('Confirmed');
  drupal_exit();
}

/**
 * Page callback for excur/offer/reject/%excur_offer
 */
function excur_offer_rejected($offer) {
  excur_offer_update($offer->id, 'status', EXCUR_OFFER_REJECTED);
  $account = user_load($offer->uid);
  $message = t('Guide has rejected your order.');
  excur_offer_send_mail($account->mail, $message);
  print t('Rejected');
  drupal_exit();
}

/**
 * Page callback for excur/offer/%excur_offer path.
 */
function excur_offer_page($offer) {
  print theme('offer_mail', array('offer' => $offer));
  drupal_exit();
}

/**
 * Page callback for excur/offer/%order.
 */
function excur_offer_order($order){
    return theme('order_template', array('order' => $order));    
}

/**
 * Form builder for offer form.
 */
function excur_offer_offer_form($form, &$form_state, $offer) {

  $form_state['#data'] = $offer;
  $form['#data'] = $offer;

  foreach ($offer['tickets'] as $key => $ticket) {
    $options[(string) $key] = $ticket['title'] . ' (' . $ticket['price'] . ' ' . $offer['currency'] . ')';
  }
  $form['tickets'] = array(
    '#type' => 'radios',
    '#options' => $options,
  );

  $form['date'] = array(
    '#title' => t('Сhoose a date'),
    '#type' => 'date_popup',
    '#default_value' => date('Y-m-d'),
    '#date_format' => 'Y-m-d',
    '#date_year_range' => '-0:+1',
    '#date_label_position' => 'within',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Reserve'),
    '#attributes' => array(
      'class' => array('btn'),
    ),
  );
  $form['#submit'][] = 'excur_offer_offer_form_submit';
  $form['#validate'][] = 'excur_offer_offer_form_validate';

  return $form;
}

/**
 * Form builder for order form.
 */
function excur_offer_order_form($form, $offer, $order) {
  global $user;

  $options_languages = array();
  $private_place = $order->field_private_place['und'][0]['value'];
  $language_list = $order->field_languages['und'];
  $data_content = array();

  foreach ($language_list as $key => $tid) {
    $languages = taxonomy_term_load($tid['tid']);
    $options_languages[$key] = $languages->name;
  }
  if($private_place == 1){
    $form['venue'] = array(
      '#type'	=> 'textfield',
      '#title' => t('Meeting point'),
      '#default_value' => t(''),
    );
  }
  $form['language'] = array(
    '#type' => 'select',
    '#title' => t('Language'),
    '#options' => $options_languages,
    '#default_value' => url(current_path(), array('absolute' => TRUE)),
    '#data-content' => $data_content,
  );
  $form['name'] = array(
    '#type'	=> 'textfield',
    '#title' => t('Name'),
    '#default_value' => $user->name,
  );
  $form['email'] = array(
    '#type'	=> 'textfield',
    '#title' => t('E-mail'),
    '#default_value' => $user->mail,
  );
  $form['phone'] = array(
    '#type'	=> 'textfield',
    '#title' => t('Phone  '),
    '#default_value' => t(''),
  );
  $form['tourist_name'] = array(
    '#type'	=> 'textfield',
    '#title' => t('Name'),
    '#default_value' => $user->name,
  );
  $form['tourist_email'] = array(
    '#type'	=> 'textfield',
    '#title' => t('E-mail'),
    '#default_value' => $user->mail,
  );
  $form['tourist_phone'] = array(
    '#type'	=> 'textfield',
    '#title' => t('Phone  '),
    '#default_value' => t(''),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Reserve'),
    '#attributes' => array(
      'class' => array('btn'),
    ),
  );
  $form['#submit'][] = 'excur_offer_order_form_submit';
  $form['#validate'][] = 'excur_offer_order_form_validate';
  $form['#theme'] = 'excur_offer_order_form_validate';

  return $form;
}

/**
 * Validate callback for excur_offer_order_form() form.
 */
function excur_offer_order_form_validate(&$form) {
  if (!$form['venue']['value']) {
    form_error($form['venue'], t('Укажите место встречи'));
  }
  if (!$form['name']['value']) {
    form_error($form['name'], t('Укажите имя'));
  }
  if (!$form['email']['value']) {
    form_error($form['venue'], t('Укажите email'));
  }
}

/**
 * Submit callback for excur_offer_order_form() form.
 */
function excur_offer_order_form_submit(&$form, &$form_state) {


}

/**
 * Validate callback for excur_offer_offer_form() form.
 */
function excur_offer_offer_form_validate(&$form, &$form_state) {
  $values = $form_state['values'];
  if (!$values['tickets']) {
    form_error($form['tickets'], t('You should choose a price.'));
  }
  if (!$values['date'] || strtotime($values['date']) < REQUEST_TIME) {
    form_error($form['date'], t('You should choose a valid date.'));
  }
}

/**
 * Submit callback for excur_offer_offer_form() form.
 */
function excur_offer_offer_form_submit(&$form, &$form_state) {
  global $user;

  $values = $form_state['values'];
  $nid = $form['#data']['nid'];
  $duration = $form['#data']['duration'];
  $type_offer = $form['#data']['title'];
  foreach($form['#data']['tickets'] as $key=>$value){
    if($values['tickets']== $key){
      $ticket_type = $value['title'];
    }
  }
  $language = 0;
  $oid = rand(1000, 9999) . REQUEST_TIME;
  $id = excur_offer_save($oid, $user->uid, $form['#data']['nid'], $values['tickets'], excur_offer_user_currency(), $values['date'], 0, $language, $type_offer, $ticket_type, $duration);
  drupal_goto('excur/offer/order/' . $nid, array('query' => array('id' => $id)));
}

/**
 * Send html mail.
 */
function excur_offer_send_mail($email, $message, $subject = NULL, $module_key = NULL) {
  $subject = $subject
    ? $subject
    : t('Уведомление от сайта "!site"', array('!site' => variable_get('site_name')));

  $module = 'excur_offer';
  $module_key = $module_key ? $module_key : 'offer_mail';
  $from = variable_get('site_mail');
  $message = array(
    'id' => $module . '_' . $module_key,
    'to' => $email,
    'subject' => $subject,
    'body' => array($message),
    'from' => $from,
    'headers' => array(
      'MIME-Version' => '1.0',
      'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
      'Content-Transfer-Encoding' => '8Bit',
      'X-Mailer' => 'Drupal',
      'From' => $from,
      'Sender' => $from,
      'Return-Path' => $from,
    ),
  );
  $system = drupal_mail_system($module, $module_key);
  $message = $system->format($message);

  return $system->mail($message);
}

/**
 * Load offer.
 *
 * @param int $oid.
 * @return object.
 */
function excur_offer_load($id) {
  return db_select('excur_offer', 'eo')
    ->fields('eo')
    ->condition('id', $id)
    ->execute()
    ->fetchObject();
}

/**
 * Save offer.
 *
 * @param string $oid.
 * @param int $uid.
 * @param int $nid.
 * @param string $ticket.
 * @param string $currency.
 * @param string $date.
 * @param string $status.
 *
 */
function excur_offer_save($oid, $uid, $nid, $ticket, $currency, $date, $status, $language, $offer, $ticket_type, $duration) {
  $record = array(
    'oid' => $oid,
    'uid' => $uid,
    'nid' => $nid,
    'date' => $date,
    'ticket' => $ticket,
    'currency' => $currency,
    'created' => REQUEST_TIME,
    'status' => $status,
    'language' => $language,
    'offer' => $offer,
    'ticket_type' => $ticket_type,
    'duration' => $duration,
  );

  $id = db_insert('excur_offer')
    ->fields($record)
    ->execute();
  return $id;
}

/**
 * Update offer by oid.
 *
 * @param int $oid.
 * @param string $label.
 * @param mixed $value.
 */
function excur_offer_update($id, $label, $value) {
  db_update('excur_offer')
    ->fields(array($label => $value))
    ->condition('id', $id)
    ->execute();
}

/**
 * Get service duration of offer by price.
 *
 * @param float $price.
 * @param int $nid.
 * @return string.
 */
function excur_offer_duration_by_price($price, $nid) {
  global $language;

  $query = db_select('field_data_field_offer_duration', 'duration');
  $query->fields('duration', array('field_offer_duration_value'));
  $query->join('field_data_field_offer', 'offer', 'offer.field_offer_value = duration.entity_id');
  $query->join('field_data_field_offer_ticket', 'ticket', 'offer.field_offer_value = ticket.entity_id');
  $query->join('field_data_field_offer_ticket_price', 'ticket_price', 'ticket.field_offer_ticket_value = ticket_price.entity_id');
  $query->condition('offer.entity_id', $nid);
  $query->condition('ticket_price.field_offer_ticket_price_value', $price);
  $query->condition('duration.language', $language->language);

  return $query->execute()->fetchField();
}

/**
 * Check if user ordered service of current guide.
 */
function excur_offer_is_user_ordered($guide_uid, $uid = NULL) {
  global $user;
  $uid = $uid ? $uid : $user->uid;

  $query = db_select('excur_offer', 'eo');
  $query->join('field_data_field_guide', 'fdfg', 'fdfg.entity_id = eo.nid');
  $query->fields('eo', array('uid'));
  $query->condition('eo.uid', $uid);
  $query->condition('fdfg.field_guide_target_id', $guide_uid);
  $query->range(0, 1);

  return (bool) $query->execute()->fetchField();
}
