<?php

/**
 * @file.
 */

/**
 * Implements hook_menu().
 */
function excur_offer_menu() {
  $items['excur/offer/%excur_offer'] = array(
    'title' => 'E-ticket',
    'page callback' => 'excur_offer_page',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implement hook_theme().
 */
function excur_offer_theme() {
  $items['excur_offer_offer_form'] = array(
    'template' => 'theme/offer-form',
    'render element' => 'form',
  );

  $items['offer_mail'] = array(
    'file' => 'theme.inc',
    'path' => drupal_get_path('module', 'excur_offer') . '/theme',
    'variables' => array(
      'offer' => NULL,
    ),
    'template' => 'offer-mail',
  );

  return $items;
}

/**
 * Implements hook_views_api().
 */
function excur_offer_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Page callback for excur/offer/%excur_offer path.
 */
function excur_offer_page($offer) {

  print theme('offer_mail', array(
    'offer' => $offer,
  ));
  drupal_exit();
}

/**
 * Form builder for offer form.
 */
function excur_offer_offer_form($form, &$form_state, $offer) {
  $form_state['#data'] = $offer;
  $form['#data'] = $offer;

  foreach ($offer['tickets'] as $key => $ticket) {
    $options[(string) $key] = $ticket['title'] . ' (' . $ticket['price'] . ' ' . $offer['currency'] . ')';
  }
  $form['tickets'] = array(
    '#type' => 'radios',
    '#options' => $options,
  );

  $form['date'] = array(
    '#title' => t('Сhoose a date'),
    '#type' => 'date_popup',
    '#default_value' => date('Y-m-d'),
    '#date_format' => 'Y-m-d',
    '#date_year_range' => '-0:+1',
    '#date_label_position' => 'within',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Reserve'),
    '#attributes' => array(
      'class' => array('btn'),
    ),
  );
  $form['#submit'][] = 'excur_offer_offer_form_submit';
  $form['#submit'][] = 'excur_offer_offer_form_validate';

  return $form;
}

/**
 * Validate callback for excur_offer_offer_form() form.
 */
function excur_offer_offer_form_validate(&$form, &$form_state) {
  $values = $form_state['values'];
  if (!$values['tickets']) {
    form_error($form['tickets'], t('You should choose a price.'));
  }
  if (!$values['date'] || strtotime($values['date']) < REQUEST_TIME) {
    form_error($form['date'], t('You should choose a valid date.'));
  }
}

/**
 * Submit callback for excur_offer_offer_form() form.
 */
function excur_offer_offer_form_submit(&$form, &$form_state) {
  global $user;
  $values = $form_state['values'];

  $oid = rand(1000, 9999) . REQUEST_TIME;
  excur_offer_save($oid, $user->uid, $form['#data']['nid'], $values['tickets'], excur_offer_user_currency(), $values['date']);
  $offer = excur_offer_load($oid);

  $message = theme('offer_mail', array(
    'offer' => $offer,
  ));

  if (excur_offer_send_mail($user->mail, $message)) {
    drupal_set_message(t('Further instructions sent to your email.'));
  }
  else {
    drupal_set_message(t('Error occurred while you reserved order, please, try again later.'), 'warning');
  }
}

/**
 * Send html mail.
 */
function excur_offer_send_mail($email, $message, $subject = NULL, $module_key = NULL) {
  $subject = $subject
    ? $subject
    : t('Уведомление от сайта "!site"', array('!site' => variable_get('site_name')));

  $module = 'excur_offer';
  $module_key = $module_key ? $module_key : 'offer_mail';
  $from = variable_get('site_mail');
  $message = array(
    'id' => $module . '_' . $module_key,
    'to' => $email,
    'subject' => $subject,
    'body' => array($message),
    'from' => $from,
    'headers' => array(
      'MIME-Version' => '1.0',
      'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
      'Content-Transfer-Encoding' => '8Bit',
      'X-Mailer' => 'Drupal',
      'From' => $from,
      'Sender' => $from,
      'Return-Path' => $from,
    ),
  );
  $system = drupal_mail_system($module, $module_key);
  $message = $system->format($message);

  return $system->mail($message);
}

/**
 * Load offer.
 *
 * @param int $oid.
 * @return object.
 */
function excur_offer_load($oid) {
  return db_select('excur_offer', 'eo')
    ->fields('eo')
    ->condition('oid', $oid)
    ->execute()
    ->fetchObject();
}

/**
 * Save offer.
 *
 * @param string $oid.
 * @param int $uid.
 * @param int $nid.
 * @param string $ticket.
 * @param string $currency.
 * @param string $date.
 */
function excur_offer_save($oid, $uid, $nid, $ticket, $currency, $date) {
  $record = array(
    'oid' => $oid,
    'uid' => $uid,
    'nid' => $nid,
    'date' => $date,
    'ticket' => $ticket,
    'currency' => $currency,
    'created' => REQUEST_TIME,
  );

  db_insert('excur_offer')
    ->fields($record)
    ->execute();
}

/**
 * Get service duration of offer by price.
 *
 * @param float $price.
 * @param int $nid.
 * @return string.
 */
function excur_offer_duration_by_price($price, $nid) {
  global $language;

  $query = db_select('field_data_field_offer_duration', 'duration');
  $query->fields('duration', array('field_offer_duration_value'));
  $query->join('field_data_field_offer', 'offer', 'offer.field_offer_value = duration.entity_id');
  $query->join('field_data_field_offer_ticket', 'ticket', 'offer.field_offer_value = ticket.entity_id');
  $query->join('field_data_field_offer_ticket_price', 'ticket_price', 'ticket.field_offer_ticket_value = ticket_price.entity_id');
  $query->condition('offer.entity_id', $nid);
  $query->condition('ticket_price.field_offer_ticket_price_value', $price);
  $query->condition('duration.language', $language->language);

  return $query->execute()->fetchField();
}
